### ISSUE TITLE
Database Interface

### ISSUE THREAD

**Issue by ZeroKnight** [ZeroKnight/ZeroBot#10]
More or less a continuation/refactor of the ideas originally started in the [Perl incarnation](https://github.com/ZeroKnight/ZeroBot-Perl/blob/master/ZeroBot/Database.pm).

# Task List

- [x] Implement design
- [x] Implement backup functionality
- [x] Proper restructure of existing `zerobot.sqlite`, e.g. proper normalization and "global" tables
- [x] Import old data into the new structure
- [x] Import backlogged module data, transforming into proper formatting as necessary, e.g. quotes

# Design

ZeroBot shall make use of a monolithic `zerobot.sqlite` database with some core-related tables (?), global tables usable by all modules, and module-specific tables. I'm currently not sure what the core tables would hold, and may just merge this concept into the global tables.

Each module (and the Core) will have its own connection to the database. A `ZeroBot.database` method will be responsible for initializing these connections, and the core will deliver these connection objects to modules that request them.

Modules that make use of the database _should_ adhere to a table naming convention such that modules with a single or primary table have a name equal to their module identifier, e.g. `chat`. Modules may create additional tables, but the names _should_ always prefix these table names with their identifier, e.g. `chat_triggers`.

## Implementation Details

`ZeroBot.database.Connection` shall extend `sqlite3.Connection` in order to associate the module that the connection is for, and facilitate synchronization of any state with Core.

Connections are requested by modules via a method like `Core.database_connect`, typically within their `module_register` callback. This method shall call `ZeroBot.database.create_connection`, which handles creating and setting up an `sqlite3.Connection` object. A dictionary within Core will map module identifiers to these resultant connection objects. Modules may close their connection manually, but the Core will ensure that this is done during shutdown and module reload.

Once a module is connected, it may execute any arbitrary queries it wants. Connection creation and closure should be logged, probably in `INFO`.

Database transactions should be logged, with the executing module included in the message. DQL statements should go to `DEBUG`, and DML/DDL should go to `INFO`. Can achieve this through light extension of `sqlite3.Connection.execute*` methods. TCL statements should be logged as well, but probably only `commit` and `rollback` warrant being sent to `INFO`; the rest can be sent to `DEBUG`.

## Table Access [Deprecated]

**NOTE**: I've since decided against this. The enforcement offered is rather superficial, as a module could simply reset the authorizer to a dummy callback or make its own connection directly. With this in mind, writing the authorizer and the config logic around granting modules access becomes a bit of a waste of effort, as modules can realistically do whatever they want anyway; as the saying goes: "we're all consenting adults here". ZeroBot's modules are intended to be able to interact anyway. Modules can of course still use `set_authorizer` to implement validation, if they wish to do so.

I'm leaving these notes here anyway for reference.

Table access can be controlled via [`sqlite3.Connection.set_authorizer`](https://docs.python.org/3/library/sqlite3.html#sqlite3.Connection.set_authorizer). A callback will be defined in ZeroBot.database that authorizes transactions in the following ways:

- The affected table name is checked against the executing module and will allow the transaction only if:
  - The module's identifier matches the whole table name or its prefix
  - The module is explicitly granted permission to the table in ZeroBot's config
  - The table is global
  - Otherwise, the transaction is rejected.
- A module may only create extra tables with a prefix matching its identifier, rejecting otherwise.
